# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/fascinate/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/samsung/fascinate/proprietary/lib/libsecril-client.so:obj/lib/libsecril-client.so \
    vendor/samsung/fascinate/proprietary/lib/libcamera.so:obj/lib/libcamera.so

#
# Wifi
#
PRODUCT_COPY_FILES += \
    vendor/samsung/fascinate/proprietary/lib/libwlservice.so:system/lib/libwlservice.so \
    vendor/samsung/fascinate/proprietary/lib/libwpa_client.so:system/lib/libwpa_client.so \
    vendor/samsung/fascinate/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/fascinate/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/fascinate/proprietary/etc/wifi/bcm4329_aps.bin:system/etc/wifi/bcm4329_aps.bin \
    vendor/samsung/fascinate/proprietary/etc/wifi/bcm4329_mfg.bin:system/etc/wifi/bcm4329_mfg.bin \
    vendor/samsung/fascinate/proprietary/etc/wifi/bcm4329_sta.bin:system/etc/wifi/bcm4329_sta.bin \
    vendor/samsung/fascinate/proprietary/etc/wifi/wifi.conf:system/etc/wifi/wifi.conf \
    vendor/samsung/fascinate/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/fascinate/proprietary/bin/wlservice:system/bin/wlservice \
    vendor/samsung/fascinate/proprietary/bin/wpa_supplicant:system/bin/wpa_supplicant

#
# Display (3D)
#
PRODUCT_COPY_FILES += \
    vendor/samsung/fascinate/proprietary/bin/pvrsrvinit:system/bin/pvrsrvinit \
    vendor/samsung/fascinate/proprietary/lib/egl/libEGL_POWERVR_SGX540_120.so:system/lib/egl/libEGL_POWERVR_SGX540_120.so \
    vendor/samsung/fascinate/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/samsung/fascinate/proprietary/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so:system/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so \
    vendor/samsung/fascinate/proprietary/lib/egl/libGLESv2_POWERVR_SGX540_120.so:system/lib/egl/libGLESv2_POWERVR_SGX540_120.so \
    vendor/samsung/fascinate/proprietary/lib/libsrv_um.so:system/lib/libsrv_um.so \
    vendor/samsung/fascinate/proprietary/lib/libsrv_init.so:system/lib/libsrv_init.so \
    vendor/samsung/fascinate/proprietary/lib/libIMGegl.so:system/lib/libIMGegl.so \
    vendor/samsung/fascinate/proprietary/lib/libpvr2d.so:system/lib/libpvr2d.so \
    vendor/samsung/fascinate/proprietary/lib/libpvrANDROID_WSEGL.so:system/lib/libpvrANDROID_WSEGL.so \
    vendor/samsung/fascinate/proprietary/lib/libglslcompiler.so:system/lib/libglslcompiler.so \
    vendor/samsung/fascinate/proprietary/lib/libPVRScopeServices.so:system/lib/libPVRScopeServices.so

#
# Sensors, Lights etc
#
PRODUCT_COPY_FILES += \
    vendor/samsung/fascinate/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/samsung/fascinate/proprietary/lib/hw/gralloc.s5pc110.so:system/lib/hw/gralloc.s5pc110.so \
    vendor/samsung/fascinate/proprietary/lib/libsensor_yamaha.so:system/lib/libsensor_yamaha.so \
    vendor/samsung/fascinate/proprietary/lib/libsensor_yamaha_test.so:system/lib/libsensor_yamaha_test.so \
    vendor/samsung/fascinate/proprietary/lib/libms3c_yamaha.so:system/lib/libms3c_yamaha.so \
    vendor/samsung/fascinate/proprietary/bin/sensorcalibutil_yamaha:system/bin/sensorcalibutil_yamaha \
    vendor/samsung/fascinate/proprietary/bin/sensorserver_yamaha:system/bin/sensorserver_yamaha \
    vendor/samsung/fascinate/proprietary/bin/sensorstatutil_yamaha:system/bin/sensorstatutil_yamaha
#    vendor/samsung/fascinate/proprietary/lib/hw/copybit.s5pc110.so:system/lib/hw/copybit.s5pc110.so
#    vendor/samsung/fascinate/proprietary/lib/hw/lights.s5pc110.so:system/lib/hw/lights.s5pc110.so \

#
# Camera
#
PRODUCT_COPY_FILES += \
    vendor/samsung/fascinate/proprietary/lib/libarccamera.so:system/lib/libarccamera.so \
    vendor/samsung/fascinate/proprietary/lib/libcamerafirmwarejni.so:system/lib/libcamerafirmwarejni.so \
    vendor/samsung/fascinate/proprietary/lib/libseccameraadaptor.so:system/lib/libseccameraadaptor.so \
    vendor/samsung/fascinate/proprietary/lib/libseccamera.so:system/lib/libseccamera.so \
    vendor/samsung/fascinate/proprietary/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
    vendor/samsung/fascinate/proprietary/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv \
    vendor/samsung/fascinate/proprietary/lib/libcamera.so:system/lib/libcamera.so

#
# RIL
#
PRODUCT_COPY_FILES += \
    vendor/samsung/fascinate/proprietary/lib/libsec-ril40.so:system/lib/libsec-ril40.so \
    vendor/samsung/fascinate/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/fascinate/proprietary/etc/cdma-carriers-conf.xml:system/etc/cdma-carriers-conf.xml \
    vendor/samsung/fascinate/proprietary/xbin/ipctool:system/xbin/ipctool \
    vendor/samsung/fascinate/proprietary/bin/dhcpcd:system/bin/dhcpcd \
    vendor/samsung/fascinate/proprietary/etc/dhcpcd/dhcpcd-hooks/01-test:system/etc/dhcpcd/dhcpcd-hooks/01-test \
    vendor/samsung/fascinate/proprietary/etc/dhcpcd/dhcpcd-hooks/20-dns.conf:system/etc/dhcpcd/dhcpcd-hooks/20-dns.conf \
    vendor/samsung/fascinate/proprietary/etc/dhcpcd/dhcpcd-hooks/95-configured:system/etc/dhcpcd/dhcpcd-hooks/95-configured \
    vendor/samsung/fascinate/proprietary/etc/dhcpcd/dhcpcd-run-hooks:system/etc/dhcpcd/dhcpcd-run-hooks \
    vendor/samsung/fascinate/proprietary/etc/dhcpcd/dhcpcd.conf:system/etc/dhcpcd/dhcpcd.conf \
    vendor/samsung/fascinate/proprietary/bin/rilclient-test:system/bin/rilclient-test \
    vendor/samsung/fascinate/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/fascinate/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/fascinate/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so

#
# PPP
#
PRODUCT_COPY_FILES += \
    vendor/samsung/fascinate/proprietary/bin/pppd_runner:system/bin/pppd_runner \
    vendor/samsung/fascinate/proprietary/etc/init.cdma-pppd:system/etc/init.cdma-pppd \
    vendor/samsung/fascinate/proprietary/etc/init.gprs-pppd:system/etc/init.gprs-pppd \
    vendor/samsung/fascinate/proprietary/etc/ppp/chap-secrets:system/etc/ppp/chap-secrets \
    vendor/samsung/fascinate/proprietary/etc/ppp/ip-up:system/etc/ppp/ip-up \
    vendor/samsung/fascinate/proprietary/etc/ppp/ip-down:system/etc/ppp/ip-down \
    vendor/samsung/fascinate/proprietary/etc/ppp/ip-up-vpn:system/etc/ppp/ip-up-vpn \
    vendor/samsung/fascinate/proprietary/etc/ppp/pap-secrets:system/etc/ppp/pap-secrets \
    vendor/samsung/fascinate/proprietary/etc/ppp/options:system/etc/ppp/options

#
# OMX
#
PRODUCT_COPY_FILES += \
    vendor/samsung/fascinate/proprietary/lib/libs263domxoc.so:system/lib/libs263domxoc.so \
    vendor/samsung/fascinate/proprietary/lib/libs263eomxoc.so:system/lib/libs263eomxoc.so \
    vendor/samsung/fascinate/proprietary/lib/libs264domxoc.so:system/lib/libs264domxoc.so \
    vendor/samsung/fascinate/proprietary/lib/libs264eomxoc.so:system/lib/libs264eomxoc.so \
    vendor/samsung/fascinate/proprietary/lib/libsaacdomxoc.so:system/lib/libsaacdomxoc.so \
    vendor/samsung/fascinate/proprietary/lib/libsaaceomxoc.so:system/lib/libsaaceomxoc.so \
    vendor/samsung/fascinate/proprietary/lib/libsac3domxoc.so:system/lib/libsac3domxoc.so \
    vendor/samsung/fascinate/proprietary/lib/libsamrdomxoc.so:system/lib/libsamrdomxoc.so \
    vendor/samsung/fascinate/proprietary/lib/libsamreomxoc.so:system/lib/libsamreomxoc.so \
    vendor/samsung/fascinate/proprietary/lib/libsdiv3domxoc.so:system/lib/libsdiv3domxoc.so \
    vendor/samsung/fascinate/proprietary/lib/libsflacdomxoc.so:system/lib/libsflacdomxoc.so \
    vendor/samsung/fascinate/proprietary/lib/libsmp3domxoc.so:system/lib/libsmp3domxoc.so \
    vendor/samsung/fascinate/proprietary/lib/libsmp4fmocn.so:system/lib/libsmp4fmocn.so \
    vendor/samsung/fascinate/proprietary/lib/libsmp4vdomxoc.so:system/lib/libsmp4vdomxoc.so \
    vendor/samsung/fascinate/proprietary/lib/libsmp4veomxoc.so:system/lib/libsmp4veomxoc.so \
    vendor/samsung/fascinate/proprietary/lib/libsvc1domxoc.so:system/lib/libsvc1domxoc.so \
    vendor/samsung/fascinate/proprietary/lib/libswmadomxoc.so:system/lib/libswmadomxoc.so \
    vendor/samsung/fascinate/proprietary/lib/libswmv7domxoc.so:system/lib/libswmv7domxoc.so \
    vendor/samsung/fascinate/proprietary/lib/libswmv8domxoc.so:system/lib/libswmv8domxoc.so \
    vendor/samsung/fascinate/proprietary/lib/libomx_evrcdec_sharedlibrary.so:system/lib/libomx_evrcdec_sharedlibrary.so \
    vendor/samsung/fascinate/proprietary/lib/libomx_evrcenc_sharedlibrary.so:system/lib/libomx_evrcenc_sharedlibrary.so \
    vendor/samsung/fascinate/proprietary/lib/libomx_qcelpdec_sharedlibrary.so:system/lib/libomx_qcelpdec_sharedlibrary.so \
    vendor/samsung/fascinate/proprietary/lib/libomx_qcelpenc_sharedlibrary.so:system/lib/libomx_qcelpenc_sharedlibrary.so \
    vendor/samsung/fascinate/proprietary/bin/pv2way_omx_engine_test:system/bin/pv2way_omx_engine_test \
    vendor/samsung/fascinate/proprietary/lib/libomadrm.so:system/lib/libomadrm.so \
    vendor/samsung/fascinate/proprietary/lib/libomx_avcenc_sharedlibrary.so:system/lib/libomx_avcenc_sharedlibrary.so \
    vendor/samsung/fascinate/proprietary/lib/libomx_m4venc_sharedlibrary.so:system/lib/libomx_m4venc_sharedlibrary.so \
    vendor/samsung/fascinate/proprietary/lib/libopencore_2way.so:system/lib/libopencore_2way.so \
    vendor/samsung/fascinate/proprietary/lib/libsavidocn.so:system/lib/libsavidocn.so \
    vendor/samsung/fascinate/proprietary/lib/libsavidreg.so:system/lib/libsavidreg.so \
    vendor/samsung/fascinate/proprietary/lib/libsavsac.so:system/lib/libsavsac.so \
    vendor/samsung/fascinate/proprietary/lib/libsavscmn.so:system/lib/libsavscmn.so \
    vendor/samsung/fascinate/proprietary/lib/libsavsff.so:system/lib/libsavsff.so \
    vendor/samsung/fascinate/proprietary/lib/libsavsvc.so:system/lib/libsavsvc.so \
    vendor/samsung/fascinate/proprietary/lib/libSecOMXCore.so:system/lib/libSecOMXCore.so \
    vendor/samsung/fascinate/proprietary/lib/libsflacfdocn.so:system/lib/libsflacfdocn.so \
    vendor/samsung/fascinate/proprietary/lib/libsflacfdreg.so:system/lib/libsflacfdreg.so \
    vendor/samsung/fascinate/proprietary/lib/libsflvdocn.so:system/lib/libsflvdocn.so \
    vendor/samsung/fascinate/proprietary/lib/libsflvdreg.so:system/lib/libsflvdreg.so \
    vendor/samsung/fascinate/proprietary/lib/libsmkvdocn.so:system/lib/libsmkvdocn.so \
    vendor/samsung/fascinate/proprietary/lib/libsmkvdreg.so:system/lib/libsmkvdreg.so \
    vendor/samsung/fascinate/proprietary/lib/libsolocore_androidpv.so:system/lib/libsolocore_androidpv.so \
    vendor/samsung/fascinate/proprietary/lib/libsolocore_common.so:system/lib/libsolocore_common.so \
    vendor/samsung/fascinate/proprietary/lib/libsolocore_downloadreg.so:system/lib/libsolocore_downloadreg.so \
    vendor/samsung/fascinate/proprietary/lib/libsolocore_download.so:system/lib/libsolocore_download.so \
    vendor/samsung/fascinate/proprietary/lib/libsolocore_mp4localreg.so:system/lib/libsolocore_mp4localreg.so \
    vendor/samsung/fascinate/proprietary/lib/libsolocore_mp4local.so:system/lib/libsolocore_mp4local.so \
    vendor/samsung/fascinate/proprietary/lib/libsolocore_net_support.so:system/lib/libsolocore_net_support.so \
    vendor/samsung/fascinate/proprietary/lib/libsolocore_player.so:system/lib/libsolocore_player.so \
    vendor/samsung/fascinate/proprietary/lib/libsolocore_pvme.so:system/lib/libsolocore_pvme.so \
    vendor/samsung/fascinate/proprietary/lib/libsolocore_streamingreg.so:system/lib/libsolocore_streamingreg.so \
    vendor/samsung/fascinate/proprietary/lib/libsolocore_streaming.so:system/lib/libsolocore_streaming.so \
    vendor/samsung/fascinate/proprietary/lib/libsolohw.so:system/lib/libsolohw.so \
    vendor/samsung/fascinate/proprietary/lib/libsoloomx_sharedlibrary.so:system/lib/libsoloomx_sharedlibrary.so \
    vendor/samsung/fascinate/proprietary/lib/libsoloomx_wmadec_sharedlibrary.so:system/lib/libsoloomx_wmadec_sharedlibrary.so \
    vendor/samsung/fascinate/proprietary/lib/libsoloomx_wmvdec_sharedlibrary.so:system/lib/libsoloomx_wmvdec_sharedlibrary.so \
    vendor/samsung/fascinate/proprietary/lib/libsoloomx_wrapper_sharedlibrary.so:system/lib/libsoloomx_wrapper_sharedlibrary.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvasfcommon.so:system/lib/libsolopvasfcommon.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvasflocalpbreg.so:system/lib/libsolopvasflocalpbreg.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvasflocalpb.so:system/lib/libsolopvasflocalpb.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvasxparser_extn.so:system/lib/libsolopvasxparser_extn.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvdbconfigclass.so:system/lib/libsolopvdbconfigclass.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvdb_recovery_utility.so:system/lib/libsolopvdb_recovery_utility.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvdb.so:system/lib/libsolopvdb.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvdla_extn.so:system/lib/libsolopvdla_extn.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvgetmetadata_extn.so:system/lib/libsolopvgetmetadata_extn.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopviptransport.so:system/lib/libsolopviptransport.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvjanus.so:system/lib/libsolopvjanus.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvmshttp_streamingreg.so:system/lib/libsolopvmshttp_streamingreg.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvmshttp_streaming.so:system/lib/libsolopvmshttp_streaming.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvmtpconfigclass.so:system/lib/libsolopvmtpconfigclass.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvmtpdrmmanagerplugin.so:system/lib/libsolopvmtpdrmmanagerplugin.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvmtpip.so:system/lib/libsolopvmtpip.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvmtp_jni.so:system/lib/libsolopvmtp_jni.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvmtpservice.so:system/lib/libsolopvmtpservice.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvmtp.so:system/lib/libsolopvmtp.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvmtp_usb_transport.so:system/lib/libsolopvmtp_usb_transport.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvplaybackcontrol_extn.so:system/lib/libsolopvplaybackcontrol_extn.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvprotocolengine_asfstreamingreg.so:system/lib/libsolopvprotocolengine_asfstreamingreg.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvprotocolengine_asfstreaming.so:system/lib/libsolopvprotocolengine_asfstreaming.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvsetparameter_extn.so:system/lib/libsolopvsetparameter_extn.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvupnp.so:system/lib/libsolopvupnp.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvwmdrm_jni.so:system/lib/libsolopvwmdrm_jni.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvwmdrmoemsettings.so:system/lib/libsolopvwmdrmoemsettings.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvwmdrmservice.so:system/lib/libsolopvwmdrmservice.so \
    vendor/samsung/fascinate/proprietary/lib/libsolopvwmdrm.so:system/lib/libsolopvwmdrm.so \
    vendor/samsung/fascinate/proprietary/lib/libswmfdocn.so:system/lib/libswmfdocn.so \
    vendor/samsung/fascinate/proprietary/lib/libswmfdreg.so:system/lib/libswmfdreg.so \
    vendor/samsung/fascinate/proprietary/lib/libQmageDecoder.so:system/lib/libQmageDecoder.so \
    vendor/samsung/fascinate/proprietary/lib/libquramgifmovie.so:system/lib/libquramgifmovie.so \
    vendor/samsung/fascinate/proprietary/lib/libquramimagecodec.so:system/lib/libquramimagecodec.so \
    vendor/samsung/fascinate/proprietary/lib/libquramvdecoder.so:system/lib/libquramvdecoder.so

#
# Voice Search
#
PRODUCT_COPY_FILES += \
    vendor/samsung/fascinate/proprietary/tts/lang_pico/en-US_lh0_sg.bin:system/tts/lang_pico/en-US_lh0_sg.bin \
    vendor/samsung/fascinate/proprietary/tts/lang_pico/en-US_ta.bin:system/tts/lang_pico/en-US_ta.bin \
    vendor/samsung/fascinate/proprietary/tts/lang_pico/es-ES_zl0_sg.bin:system/tts/lang_pico/es-ES_zl0_sg.bin \
    vendor/samsung/fascinate/proprietary/tts/lang_pico/es-ES_ta.bin:system/tts/lang_pico/es-ES_ta.bin

#
# Other stuff
#
PRODUCT_COPY_FILES += \
    vendor/samsung/fascinate/proprietary/bin/immvibed:system/bin/immvibed \
    vendor/samsung/fascinate/proprietary/lib/libImmVibeJ.so:system/lib/libImmVibeJ.so \
    vendor/samsung/fascinate/proprietary/lib/libImmVibe.so:system/lib/libImmVibe.so \
    vendor/samsung/fascinate/proprietary/lib/libhardware.so:system/lib/libhardware.so \
    vendor/samsung/fascinate/proprietary/lib/libhardware_legacy.so:system/lib/libhardware_legacy.so \
    vendor/samsung/fascinate/proprietary/lib/libskiagl.so:system/lib/libskiagl.so \
    vendor/samsung/fascinate/proprietary/bin/BCM4329B1_002.002.023.0417.0430.hcd:system/bin/BCM4329B1_002.002.023.0417.0430.hcd \
    vendor/samsung/fascinate/proprietary/bin/vold:system/bin/vold \
    vendor/samsung/fascinate/proprietary/etc/vold.conf:system/etc/vold.conf \
    vendor/samsung/fascinate/proprietary/etc/vold.fstab:system/etc/vold.fstab

#
# Files for battery charging screen
#
PRODUCT_COPY_FILES += \
    vendor/samsung/fascinate/proprietary/bin/playlpm:system/bin/playlpm \
    vendor/samsung/fascinate/proprietary/bin/charging_mode:system/bin/charging_mode \
    vendor/samsung/fascinate/proprietary/media/battery_charging_5.qmg:system/media/battery_charging_5.qmg \
    vendor/samsung/fascinate/proprietary/media/battery_charging_10.qmg:system/media/battery_charging_10.qmg \
    vendor/samsung/fascinate/proprietary/media/battery_charging_15.qmg:system/media/battery_charging_15.qmg \
    vendor/samsung/fascinate/proprietary/media/battery_charging_20.qmg:system/media/battery_charging_20.qmg \
    vendor/samsung/fascinate/proprietary/media/battery_charging_25.qmg:system/media/battery_charging_25.qmg \
    vendor/samsung/fascinate/proprietary/media/battery_charging_30.qmg:system/media/battery_charging_30.qmg \
    vendor/samsung/fascinate/proprietary/media/battery_charging_35.qmg:system/media/battery_charging_35.qmg \
    vendor/samsung/fascinate/proprietary/media/battery_charging_40.qmg:system/media/battery_charging_40.qmg \
    vendor/samsung/fascinate/proprietary/media/battery_charging_45.qmg:system/media/battery_charging_45.qmg \
    vendor/samsung/fascinate/proprietary/media/battery_charging_50.qmg:system/media/battery_charging_50.qmg \
    vendor/samsung/fascinate/proprietary/media/battery_charging_55.qmg:system/media/battery_charging_55.qmg \
    vendor/samsung/fascinate/proprietary/media/battery_charging_60.qmg:system/media/battery_charging_60.qmg \
    vendor/samsung/fascinate/proprietary/media/battery_charging_65.qmg:system/media/battery_charging_65.qmg \
    vendor/samsung/fascinate/proprietary/media/battery_charging_70.qmg:system/media/battery_charging_70.qmg \
    vendor/samsung/fascinate/proprietary/media/battery_charging_75.qmg:system/media/battery_charging_75.qmg \
    vendor/samsung/fascinate/proprietary/media/battery_charging_80.qmg:system/media/battery_charging_80.qmg \
    vendor/samsung/fascinate/proprietary/media/battery_charging_85.qmg:system/media/battery_charging_85.qmg \
    vendor/samsung/fascinate/proprietary/media/battery_charging_90.qmg:system/media/battery_charging_90.qmg \
    vendor/samsung/fascinate/proprietary/media/battery_charging_95.qmg:system/media/battery_charging_95.qmg \
    vendor/samsung/fascinate/proprietary/media/battery_charging_100.qmg:system/media/battery_charging_100.qmg \
    vendor/samsung/fascinate/proprietary/media/batteryerror.qmg:system/media/batteryerror.qmg \
    vendor/samsung/fascinate/proprietary/media/chargingwarning.qmg:system/media/chargingwarning.qmg \
    vendor/samsung/fascinate/proprietary/media/Disconnected.qmg:system/media/Disconnected.qmg

